apiVersion: 1

datasources:
  # === PROMETHEUS ===
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://eunomia-prometheus:9090
    basicAuth: false
    isDefault: true
    editable: true

  # === LOKI ===
  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    url: http://eunomia-loki:3100
    basicAuth: false
    isDefault: false
    editable: true
